### ISSUE TITLE
feature requirment

### ISSUE THREAD

**Issue by Jacky486** [hjthjthjt/RnIntentClean#4]
开启riru hide后 app无法识别到 ifw模块

**Comment by hjthjthjt** [comment]
新版 Riru 好像改了不少，我还没处理，。不过识别不到 不一定模块就用不了，可以试一试

**Comment by Jacky486** [comment]
识别不到会提示下载模块 如果没开hide是可以识别到的 手动改ifw倒是可以不过就没app方便了🤔
